# Generated by Django 5.1.1 on 2024-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_alter_user_user_login_alter_user_user_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('potion', 'Potion'), ('plante', 'Plante'), ('arme', 'Arme'), ('cle', 'Clé'), ('armure', "Pièce d'armure")], max_length=20)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
